CREATE DATABASE klinik;
USE klinik;

CREATE TABLE POLIKLINIK (
  kode_poli INTEGER PRIMARY KEY,
  nama_poli VARCHAR(20)
);

CREATE TABLE PASIEN (
  NIK INTEGER PRIMARY KEY,
  nama VARCHAR(255),
  alamat VARCHAR(255),
  sex BOOLEAN,
  BOD TIMESTAMP
);

CREATE TABLE OBAT (
  kode_obat INTEGER PRIMARY KEY,
  nama_obat VARCHAR(255),
  harga INTEGER
);

CREATE TABLE DOKTER (
  id_dokter INTEGER PRIMARY KEY,
  nama VARCHAR(30),
  sp VARCHAR(30),
  no_tlp VARCHAR(15),
  kode_poli INTEGER,
  FOREIGN KEY (kode_poli) REFERENCES POLIKLINIK(kode_poli)
);

CREATE TABLE PENDAFTARAN (
  no_antrean INTEGER PRIMARY KEY,
  kode_poli INTEGER,
  NIK INTEGER,
  tgl_daftar DATETIME,
  FOREIGN KEY (kode_poli) REFERENCES POLIKLINIK(kode_poli),
  FOREIGN KEY (NIK) REFERENCES PASIEN(NIK)
);

CREATE TABLE REKAM_MEDIS (
  no_rm INTEGER PRIMARY KEY,
  NIK INTEGER,
  kode_obat INTEGER,
  tgl_rm TIMESTAMP,
  FOREIGN KEY (NIK) REFERENCES PASIEN(NIK),
  FOREIGN KEY (kode_obat) REFERENCES OBAT(kode_obat)
);